### ISSUE TITLE
제안서 파일 PDF 요청

### ISSUE THREAD

**Issue by MisooKim2** [hyms26/CPP202309-P#1]
안녕하세요.
업로드해주신 제안서는 잘 확인하였습니다만,
pdf 파일로 변환 후 추가 업로드 부탁드립니다.

word 파일은 제가 실수로 변경해버릴 우려가 있기 때문에 pdf로 올려주시는 것이 안전합니다.

**Comment by hyms26** [comment]
안녕하세요 교수님, 말씀해주신대로 제안서를 pdf로 변환하여 추가 커밋 진행하였습니다. 감사합니다.

2023년 11월 6일 (월) 오후 8:11, MisooKim2 ***@***.***>님이 작성:
